name: UndertaleUHC
version: "1.0"
api: "1.0"
author: Z1proW
main: fr.ziprow.undertaleuhc.Main
commands:
  start:
    description: Start Undertale UHC
    usage: /start
  info:
    description: Info on your role
    usage: /info
  role:
    description: Change role mid-game
    usage: /role <role>
  items:
    description: Give items from the plugin
    usage: /items
  choosechara:
    description: Command for Determination
    usage: /choosechara
  choosefrisk:
    description: Command for Determination
    usage: /choosefrisk
  spare:
    description: Command for Frisk
    usage: /spare <joueur>
  ally:
    description: Command for integrity
    usage: /ally <joueur>
  revive:
    description: Command for Kindness
    usage: /revive
  sympa:
    description: Command for Toriel
    usage: /sympa <joueur>
  ausculter:
    description: Command for Alphys
    usage: /ausculter <joueur>
