name: UndertaleUHC
version: '${project.version}'
main: fr.ziprow.undertaleuhc.UndertaleUHC
api-version: 1.8
author: Z1proW

commands:
  uuhc:
    description:Main command for UndertaleUHC. Use /uuhc help for more info

permissions:
  template.user:
    description: Allows player to use the plugin's user features
    default: true

  template.admin:
    description: Allows player to use the plugin's admin features
    default: op
