name: UndertaleUHC
version: '${project.version}'
main: fr.ziprow.undertaleuhc.UndertaleUHC
api-version: 1.8
author: Z1proW

commands:
  undertaleuhc:
    description: Main command for UndertaleUHC. Use /uuhc help for more info
    aliases: [uuhc]

permissions:
  undertaleuhc.user:
    description: Allows player to use the plugin's user features
    default: true

  undertaleuhc.admin:
    description: Allows player to use the plugin's admin features
    default: op
